
include: package:flutter_lints/flutter.yaml

linter:

  rules:
    prefer_const_constructors: true
    avoid_print: true
    prefer_const_declarations: true
    avoid_unnecessary_containers: true
    prefer_const_literals_to_create_immutables: true
    sized_box_for_whitespace: true

    prefer_is_empty: false
    file_names: false
    library_prefixes: false
    camel_case_types: false
    constant_identifier_names: false
    library_private_types_in_public_api: false
    depend_on_referenced_packages: false

