name: superhero_app
description: Fun project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #  GetX
  get: ^4.6.5
  get_storage: ^2.0.3

  #  Storage
  flutter_secure_storage: ^5.0.2

  #  Widgets
  flutter_svg: ^1.1.6
  shimmer: ^2.0.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.0.1
  dropdown_button2: ^1.9.3
  dotted_border: ^2.0.0+3
  animations: ^2.0.7
  badges: ^3.1.1
  dropdown_search: ^4.0.1
  draggable_bottom_sheet: ^1.0.2
  search_choices: ^2.2.5
  modal_bottom_sheet: ^2.1.2


  #  Syncfusion
  syncfusion_flutter_core: ^23.1.38
  syncfusion_flutter_charts: ^23.1.38
  syncfusion_flutter_gauges: ^23.1.38

  #  Image
  extended_image: ^6.2.1

  #  Utils
  font_awesome_flutter: ^10.1.0
  intl: ^0.18.0
  http: ^0.13.4
  connectivity_plus: ^2.0.2
  flutter_dotenv: ^5.0.2
  uuid: ^3.0.7
  flutter_exit_app: ^1.1.2
  flutter_displaymode: ^0.6.0
  clipboard: ^0.1.3
  fluttertoast: ^8.2.2
  device_info_plus: ^6.0.0
  package_info_plus: ^3.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

